spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    hikari:
      maximumPoolSize: 50

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: casev2
        jdbc:
          lob:
            non_contextual_creation: true

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 6672
    virtualhost: /

queueconfig:
  inbound-queue: case.sample.inbound
  outbound-exchange: events
  rh-case-queue: case.rh.case
  rh-case-routing-key: event.case.*
  rh-uac-queue: case.rh.uac
  rh-uac-routing-key: event.uac.*
  action-scheduler-queue: case.action
  action-scheduler-routing-key-uac: event.uac.*
  action-scheduler-routing-key-case: event.case.*
  unaddressed-inbound-queue: unaddressedRequestQueue
  receipt-response-inbound-queue: Case.Responses
  action-case-queue: action.events
  consumers: 50

healthcheck:
  frequency: 1000 #milliseconds
  filename: /tmp/case-service-healthy

uacservice:
  connection:
    scheme: http
    host: localhost
    port: 8164
