spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    hikari:
      maximumPoolSize: 50

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: casev2
        jdbc:
          lob:
            non_contextual_creation: true

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 6672
    virtualhost: /

queueconfig:
  inbound-queue: case.sample.inbound
  case-event-exchange: events
  rh-case-queue: case.rh.case
  rh-uac-queue: case.rh.uac
  action-scheduler-queue: case.action
  survey-launched-queue: survey.launched
  unaddressed-inbound-queue: unaddressedRequestQueue
  receipt-response-inbound-queue: Case.Responses
  refusal-response-inbound-queue: case.refusals
  fulfilment-request-inbound-queue: case.fulfilments
  questionnaire-linked-inbound-queue: case.questionnairelinked
  action-case-queue: action.events
  uac-qid-created-queue: case.uac-qid-created
  uac-qid-created-exchange: uac-qid-created-exchange
  address-inbound-queue: case.addressQueue
  undelivered-mail-queue: case.undeliveredMailQueue
  ccs-property-listed-queue: case.ccsPropertyListedQueue
  fulfilment-confirmed-queue: case.fulfilmentConfirmed
  field-case-updated-queue: case.field.update
  deactivate-uac-queue: case.deactivate-uac
  consumers: 50
  retry-attempts: 3
  retry-delay: 1000 #milliseconds

ccsconfig:
  action-plan-id: 38a48608-1c2a-4c2b-b7bc-cb52fcbb4927
  collection-exercise-id: 6e56db3a-293d-42e6-87b7-556c6c6c92d5

healthcheck:
  frequency: 1000 #milliseconds
  filename: /tmp/case-service-healthy

uacservice:
  connection:
    scheme: http
    host: localhost
    port: 8164

  uacqid-cache-min: 500
  uacqid-fetch-count: 1000
  uacqid-get-timeout: 60   #seconds

exceptionmanager:
  connection:
    scheme: http
    host: localhost
    port: 8666

messagelogging:
  logstacktraces: false

logging:
  level:
    org.springframework.amqp.rabbit.listener.ConditionalRejectingErrorHandler: ERROR

# Skeleton cases need to know the collection exercise id and action_plan_id
censusconfig:
  collectionexerciseid: 34d7f3bb-91c9-45d0-bb2d-90afce4fc790
  actionplanid: c4415287-0e37-447b-9c3d-1a011c9fa3db

uprnconfig:
  dummyuprnprefix: 999

pubsub:
  publishtimeout: 30  # In seconds
  aims-new-address-topic: aims-new-address-topic

estabtypes: >
  HALL OF RESIDENCE,
  CARE HOME,
  HOSPITAL,
  HOSPICE,
  MENTAL HEALTH HOSPITAL,
  MEDICAL CARE OTHER,
  BOARDING SCHOOL,
  LOW/MEDIUM SECURE MENTAL HEALTH,
  HIGH SECURE MENTAL HEALTH,
  HOTEL,
  YOUTH HOSTEL,
  HOSTEL,
  MILITARY SLA,
  MILITARY US,
  RELIGIOUS COMMUNITY,
  RESIDENTIAL CHILDRENS HOME,
  EDUCATION OTHER,
  PRISON,
  IMMIGRATION REMOVAL CENTRE,
  APPROVED PREMISES,
  ROUGH SLEEPER,
  STAFF ACCOMMODATION,
  CAMPHILL,
  HOLIDAY PARK,
  HOUSEHOLD,
  SHELTERED ACCOMMODATION,
  RESIDENTIAL CARAVAN,
  RESIDENTIAL BOAT,
  GATED APARTMENTS,
  MOD HOUSEHOLDS,
  FOREIGN OFFICES,
  CASTLES,
  GRT SITE,
  MILITARY SFA,
  EMBASSY,
  ROYAL HOUSEHOLD,
  CARAVAN SITE,
  MARINA,
  TRAVELLING PERSONS,
  TRANSIENT PERSONS
