spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: casesvcv2
        jdbc:
          lob:
            non_contextual_creation: true

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 6672
    virtualhost: /

queueconfig:
  inbound-queue: exampleInboundQueue
  emit-case-event-exchange: myfanout.exchange
  emit-case-event-rh-queue: myfanout.rhqueue
  emit-case-event-action-queue: myfanout.actionqueue

healthcheck:
  frequency: 1000 #milliseconds
  filename: /tmp/case-service-healthy

iacservice:
  generate-iacs-path: /iacs
  pool-size-min: 500
  pool-size-max: 1000
  connection:
    scheme: http
    host: localhost
    port: 8121
    username: admin
    password: secret

qid:
  tranche-identifier: 2
