spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    hikari:
      maximumPoolSize: 50

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: casev2
        jdbc:
          lob:
            non_contextual_creation: true

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 6672
    virtualhost: /

queueconfig:
  inbound-queue: case.sample.inbound
  case-event-exchange: events
  rh-case-queue: case.rh.case
  rh-uac-queue: case.rh.uac
  action-scheduler-queue: case.action
  survey-launched-queue: survey.launched
  unaddressed-inbound-queue: unaddressedRequestQueue
  receipt-response-inbound-queue: Case.Responses
  refusal-response-inbound-queue: case.refusals
  fulfilment-request-inbound-queue: case.fulfilments
  questionnaire-linked-inbound-queue: case.questionnairelinked
  action-case-queue: action.events
  uac-qid-created-queue: case.uac-qid-created
  uac-qid-created-exchange: uac-qid-created-exchange
  invalid-address-inbound-queue: case.invalidAddressQueue
  undelivered-mail-queue: case.undeliveredMailQueue
  outbound-field-exchange: action-outbound-exchange
  field-binding: Action.Field.binding
  ccs-property-listed-queue: case.ccsPropertyListedQueue
  consumers: 50
  retry-attempts: 3
  retry-delay: 1000 #milliseconds
  quarantine-exchange: quarantineExchange

ccsconfig:
  action-plan-id: 38a48608-1c2a-4c2b-b7bc-cb52fcbb4927
  collection-exercise-id: 6e56db3a-293d-42e6-87b7-556c6c6c92d5

healthcheck:
  frequency: 1000 #milliseconds
  filename: /tmp/case-service-healthy

uacservice:
  connection:
    scheme: http
    host: localhost
    port: 8164

  uacqid-cache-min: 500
  uacqid-fetch-count: 1000
  uacqid-get-timeout: 5   #seconds

exceptionmanager:
  connection:
    scheme: http
    host: localhost
    port: 8666

messagelogging:
  logstacktraces: false

logging:
  level:
    org.springframework.amqp.rabbit.listener.ConditionalRejectingErrorHandler: ERROR
