package uk.gov.ons.census.casesvc.model.entity;

public enum EventType {
  UAC_UPDATED,
  PRINT_CASE_SELECTED,
  RESPONSE_RECEIVED,
  REFUSAL_RECEIVED,
  FULFILMENT_REQUESTED,
  QUESTIONNAIRE_LINKED,
  SAMPLE_LOADED,
  RM_UAC_CREATED,
  ADDRESS_NOT_VALID,
  SURVEY_LAUNCHED,
  FIELD_CASE_SELECTED
}
