package uk.gov.ons.census.casesvc.model.entity;

public enum EventType {
  CASE_CREATED,
  CASE_UPDATED,
  UAC_UPDATED,
  PRINT_CASE_SELECTED,
  RESPONSE_RECEIVED,
  REFUSAL_RECEIVED,
  FULFILMENT_REQUESTED,
  QUESTIONNAIRE_LINKED,
  SAMPLE_UNIT_VALIDATED;
}
