package uk.gov.ons.census.casesvc.model.dto;

public enum EventTypeDTO {
  CASE_CREATED,
  CASE_UPDATED,
  UAC_UPDATED,
  PRINT_CASE_SELECTED,
  RESPONSE_RECEIVED,
  REFUSAL_RECEIVED,
  FULFILMENT_REQUESTED,
  QUESTIONNAIRE_LINKED,
  SAMPLE_LOADED,
  RM_UAC_CREATED,
  ADDRESS_NOT_VALID,
  SURVEY_LAUNCHED,
  RESPONDENT_AUTHENTICATED
}
